import type { z } from 'zod';
import type { AbilityEffect } from './ability-geometry.mjs';
export type Uploader = { name: string; source: 'toy' | 'local' | 'curated'; toyOpenId?: string; bilibiliUid?: string };
export type MediaKind = 'stance' | 'aim' | 'effect';
export type MediaItem = { key: string; alt: string; original?: { key: string; sha256: string } };
export type Lineup = { id: string; mapId: string; agentId: string; abilityId: string; uploader: Uploader; title: string; side: 'attack' | 'defense'; area: string; videoBvid: string; target: { groupId: string; x: number; y: number }; effect?: AbilityEffect; instructions: string; media: Record<MediaKind, MediaItem[]> };
export type Asset = MediaItem & { lineupId: string; kind: MediaKind; mimeType: string; size: number; sha256: string };
export type Changes = { added: Lineup[]; updated: { id: string; before: Lineup; after: Lineup }[]; deleted?: { id: string; before: Lineup }[] };
export type Manifest = { format: 'valo-lineup-edit-package'; version: 4 | 5; packageId: string; revision: number; createdAt: string; updatedAt: string; author: Uploader; changes: Changes; uploadedAssets: Asset[] };
export type PackageData = { manifest: Manifest; blobs: Map<string, Blob> };
export const PACKAGE_VERSION: 5;
export const MAX_IMAGE_BYTES: number;
export const MAX_PACKAGE_BYTES: number;
export const uploaderSchema: z.ZodType<Uploader>;
export const lineupSchema: z.ZodType<Lineup>;
export const lineupsSchema: z.ZodType<Lineup[]>;
export const manifestSchema: z.ZodType<Manifest>;
export function allMedia(lineups: Lineup[]): (MediaItem & { lineupId: string; kind: MediaKind })[];
export function changedLineups(manifest: Manifest): Lineup[];
export function same(left: unknown, right: unknown): boolean;
export function applyLayers(base: Lineup[], packages: Manifest[], manual?: Manifest | null): { lineups: Lineup[]; sources: Map<string, Manifest> };
export function packageStats(manifest: Manifest): { maps: number; lineups: number; added: number; updated: number; deleted: number };
export function validateReferences(manifest: Manifest, maps: { id: string }[], agents: { id: string; abilities: { id: string }[] }[]): void;
export function sha256(bytes: ArrayBuffer | Uint8Array<ArrayBuffer>): Promise<string>;
export function verifyImage(bytes: Uint8Array, asset: Pick<Asset, 'key' | 'mimeType' | 'size'>): void;
export function readPackage(bytes: ArrayBuffer | Uint8Array<ArrayBuffer>): Promise<PackageData>;
export function collectChanges(previous: Manifest | null, start: Lineup[], current: Lineup[]): Changes;
export function compressPackage(data: PackageData, encode: (blob: Blob) => Promise<Blob>): Promise<PackageData>;
export function sameLineup(left: Lineup, right: Lineup, migrations?: Record<string, { sourceSha256: string }>): boolean;
